### ISSUE TITLE
eeprom_read returns all 0 if data length > 128

### ISSUE THREAD

**Issue by alw1746** [Naguissa/uEEPROMLib#3]
Arduino IDE 1.8.8, NodeMCU-32S, Windows 10, DS3231 RTC, uEEPROMLib 1.0.1

Attached test sketch. Sketch writes a counter value to EEPROM at START_ADDR for DATA_LENGTH.
If DATA_LENGTH = 128, results 0 - 7F displayed. But if DATA_LENGTH = 129, 0 are returned.

Given the number of bytes to read is uint8_t in the library, it should allow read up to 256 bytes.
Is 128 bytes  a limitation? 
[EEPROM_test.ino.txt](https://github.com/Naguissa/uEEPROMLib/files/4435615/EEPROM_test.ino.txt)

**Comment by Naguissa** [comment]
Hello,

I've seen there're problems when reading big chunks in one go.

A common fix is to split any read in 32 bytes max reads. I'll integrate it and do a new release.


Cheers!

**Comment by alw1746** [comment]
Ok thanks. will close this issue now.

**Comment by Naguissa** [comment]
No, no; I'm implementig internally on the library, so I'll change it when done.

I've done only a change that may affect compatibility: now on read funtion length will be a unint16_t instead a uint8_t. This will grant requesting more than 256 bytes in one call...


Cheers!

**Comment by Naguissa** [comment]
It's taking a while because I'm implementing page read/write and improving speed, I need to test changes deeply on several boards...

**Comment by Naguissa** [comment]
Fixed on new release 1.1.0.

Also I've implemented paged reads and writes in 32-bytes pages (half of RTC's EPPROM page size, but Arduino Wire buffer is 2 bytes less than necessary to handle 64 bytes pages).


Cheers!
