### ISSUE TITLE
STM32 Wire buffer can be up to 255

### ISSUE THREAD

**Issue by r-pv** [Naguissa/uEEPROMLib#6]
Hi, first thanks for your library, I've used on a few projects and it works perfectly.

So, as in the title, I use your library on the STM32 platform (using the STCore) and this core has the possibility of send up to [255 bytes on a I2C buffer](https://github.com/stm32duino/wiki/wiki/API#i2c-buffer-management). On smaller eeproms it won't matter much but on the bigger (>AT24C64)  will be noticeable. You can detect the ST core with something like:

```
#ifdef STM32_CORE_VERSION
     #define UEEPROMLIB_WIRE_MAX_RBUFFER 250
#else
...
```
I tested this on a BL24C256 (64bytes page size) and it was able to send >60bytes on 1 page write.

Thanks again.

**Comment by Naguissa** [comment]
Hello,

Thanks for the info. I'll add that as option in near future, as it also comes with its memory cost.


Cheers!
